name: bookly
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  go_router: ^11.1.2
  google_fonts: ^6.1.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/fonts/
